In [1]:
import pandas as pd

##### pandas is actually the dictionaries of list. There is a `key` and a `value` (value is list)

In [2]:
url = "../datasets/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [3]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='str')

In [4]:
da['BMXWT'].mean()     #can get a mean using `.mean()` function of pandas.

np.float64(81.34267560889516)

In [5]:
da['DMDEDUC2'].unique()  #Categorical , Ordered data

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [6]:
g = da['RIAGENDR']       #Categorical, Unordered data
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [7]:
g.unique #q holds gender data represented by 1 and 2 numbers.

<bound method Series.unique of 0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64>

# One Hot Encoding

We write the data in one hot encoding because assigning numbers to data makes it comparable because numbers are comparable.
So we represent data using vectors. Vectors are not comparable.

In [8]:
B = ['bird','cat','dog','bird','bird']

d = {'categorical' : B}

df = pd.DataFrame(d)

In [9]:
df

  categorical
0        bird
1         cat
2         dog
3        bird
4        bird

In [10]:
df['categorical']

0    bird
1     cat
2     dog
3    bird
4    bird
Name: categorical, dtype: str

### dummies is used to create columns corresponding to unique values

In [11]:
dfDummies = pd.get_dummies(df['categorical'], dtype = int, prefix = 'category')

In [12]:
dfDummies

   category_bird  category_cat  category_dog
0              1             0             0
1              0             1             0
2              0             0             1
3              1             0             0
4              1             0             0

In [13]:
dfDummies.values

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0]])